---
abstract: 'Facility for creating read-only scalars, arrays, and hashes'
author:
  - 'Leon Timmermans <fawaka@gmail.com>'
build_requires:
  Data::Dumper: 0
  File::Find: 0
  File::Temp: 0
  Test::Exception: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Const-Fast
requires:
  Carp: 0
  Scalar::Util: 0
  Storable: 0
  Sub::Exporter: 0
  perl: 5.008
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Const-Fast
  repository: git://github.com/Leont/const-fast.git
version: 0.011
